version: '2'
services:
  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_HOST=172.17.0.1
      - ADVERTISED_PORT=9092
    ports:
      - "2181:2181"
      - "9092:9092"
  db:
    image: postgres:12
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres123
  jupyter:
    image: jupyter/datascience-notebook
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - TZ=Asia/Taipei
      - db_host=db
      - db_name=postgres
      - db_userid=postgres
      - db_password=postgres123
    depends_on:
      - db
      - kafka
    volumes:
      - /Users/tungchun/py_work:/home/jovyan
    ports:
      - 8888:8888
      - 8000:8000
      - 5000:5000
    command: >
      bash -c "start.sh jupyter lab --ip=0.0.0.0"
